### PR TITLE
Added ArrayList back-end object

### PR DESCRIPTION
**Pull request by sameer**
Fixes issue #12

### CODE REVIEW

**Comment by sameer** [comment]
@Quetzi

**Comment by amadornes** [comment]
QmunityLib has been fully rewritten and BluePower is getting a rewrite now. We've already found a way around this issue, but we can't release the new QmunityLib yet, since it's not compatible with the old BluePower. We don't know how long it's going to take, but we're doing our best to do it as quickly as possible. I'm hoping it'll be mostly done by Jan 1st, although I can't assure anything.

**Comment by sameer** [comment]
But can this fix not be merged until the new version comes out?

**Comment by sameer** [comment]
@amadornes  Can you please either merge this fix or commit the rewritten QmunityLib so far?

**Comment by modmuss50** [comment]
the new QLib can be found on another branch, https://github.com/Qmunity/QmunityLib/tree/NewQL But is is NOT combatible with mods that use the old version.

**Pull request closed without merging**
